# Generated by Django 3.0.5 on 2020-05-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferapp', '0005_remove_imagepic_result_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageResult',
        ),
        migrations.AddField(
            model_name='imagepic',
            name='result',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
