# Generated by Django 3.0.5 on 2020-05-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferapp', '0006_auto_20200516_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepic',
            name='result',
            field=models.ImageField(default='None', upload_to=''),
        ),
    ]
